// Generated by CoffeeScript 2.5.1
var templated;

templated = require('self-templated');

module.exports = function() {
  return {
    module: '@nikitajs/engine/src/plugins/template',
    hooks: {
      'nikita:session:action': function(action, handler) {
        return function() {
          action = templated(action, {
            compile: false,
            partial: {
              metadata: true,
              config: true
            }
          });
          return handler.call(null, action);
        };
      }
    }
  };
};
